check: maturin-dev
  python check.py

bench-motiflet: maturin-dev
  python bench.py

maturin-dev:
  maturin develop --release

wheel:
    cd .. && cargo test
    cargo test
    just cross-wheel x86_64-unknown-linux-gnu
    just cross-wheel x86_64-unknown-linux-musl
    just cross-wheel x86_64-apple-darwin
    just cross-wheel aarch64-unknown-linux-gnu
    just cross-wheel aarch64-unknown-linux-musl
    just cross-wheel aarch64-apple-darwin

# Cross compiles (linking with zig) for the given platform
cross-wheel target:
    rustup target add {{target}}
    maturin build --release --zig --target {{target}}

