project:
  type: website

website:
  title: "ATTIMO"
  repo-url: https://github.com/Cecca/attimo
  repo-actions: [issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: pyattimo.qmd
        text: PyAttimo
      - href: https://cecca.github.io/attimo/VLDB-supplemental/
        text: VLDB supplement
    right:
      - icon: github
        href: https://github.com/Cecca/attimo
        aria-label: Attimo GitHub

format:
  html:
    theme: litera
    css: styles.css
    toc: true



